server:
  port: 6001
spring:
  application:
    name: cloud-counsumer-order

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaserver1.com:7001/eureka,http://eurekaserver2.com:7002/eureka
